# WorldPainter Configuration Dump
# Class: org.pepsoft.worldpainter.Configuration

windowBounds: Rectangle(java.awt.Rectangle[x=246,y=0,width=1024,height=876])
maximised: false
hilly: true
lava: false
goodies: true
populate: false
beaches: true
mergeWarningDisplayed: false
importWarningDisplayed: false
level: 58
waterLevel: 62
borderLevel: 62
surface: Grass
underground: Resources
worldDirectory: null
exportDirectory: null
savesDirectory: null
customObjectsDirectory: null
border: null
border2: null
pingAllowed: false
customMaterials: Material[5]
colourschemeIndex: 0
launchCount: 5
minecraftJars: HashMap(size=0)
donationStatus: null
uuid: UUID(1500fbad-b8ef-4a0e-bf39-c89e4e8f4087)
checkForUpdates: true
undoEnabled: true
defaultGridEnabled: false
defaultContoursEnabled: true
defaultViewDistanceEnabled: false
defaultWalkingDistanceEnabled: false
undoLevels: 100
defaultGridSize: 128
defaultContourSeparation: 10
defaultWidth: 5
defaultHeight: 5
defaultMaxHeight: 2032
defaultTerrainAndLayerSettings: Dimension(org.pepsoft.worldpainter.Dimension@4a9e6faf)
toolbarsLocked: false
version: 25
worldFileBackups: 3
defaultRange: 20.0
uiScale: 0.0
defaultScale: 1.0
defaultLightOrigin: NORTHWEST
maximumBrushSize: 300
eventLog: null
customLayers: ArrayList(size=0)
mixedMaterials: ArrayList(size=0)
defaultExtendedBlockIds: false
layerDirectory: null
terrainDirectory: null
heightMapsDirectory: null
masksDirectory: null
backgroundImage: null
heightMapDefaultTheme: null
defaultCreateGoodiesChest: false
defaultMapFeatures: true
defaultAllowCheats: false
defaultGenerator: null
defaultGameType: 0
defaultGeneratorOptions: null
defaultJideLayoutData: null
jideLayoutData: null
lookAndFeel: SYSTEM
overlayType: OPTIMISE_ON_LOAD
showCalloutCount: 0
recentFiles: null
recentScriptFiles: null
backgroundImageMode: REPEAT
backgroundColour: -1
showBorders: true
showBiomes: true
defaultGameTypeObj: SURVIVAL
defaultPlatform: null
exportDirectories: null
autosaveEnabled: true
autosaveDelay: 60000
autosaveInterval: 600000
defaultPlatformId: "org.pepsoft.anvil.1.20.5"
exportDirectoriesById: HashMap(size=0)
snapshotWarningDisplayed: false
beta118WarningDisplayed: false
minimumFreeSpaceForMaps: 1
autoDeleteBackups: true
defaultGeneratorObj: SeededGenerator(LARGE_BIOMES(seed=27594263))
defaultExportSettings: null
defaultResourcesMinimumLevel: 8
showDonationDialogAfter: 5
merchStoreDialogDisplayed: 0
displayedMessages: HashMap(size=0)
overlaysDirectory: null
maxThreadCount: null
viewDistance: 192
accelerationType: null
autosaveInhibited: false
safeMode: false
previousVersion: 24
eventListeners: HashMap(size=0)
